language: node_js
sudo: required
dist: trusty
cache:
  yarn: true
notifications:
  email: false

node_js: stable

stages:
  - 'Tests'
  - 'Additional Tests'
  - name: 'Deploy'
    if: branch = master AND type = push

install:
  - yarn install --no-lockfile --non-interactive

jobs:
  fail_fast: true
  include:
    - stage: 'Tests'
      name: 'Conventional Commits'
      script: commitlint-travis
    - name: 'Fixed Dependencies'
      install: yarn install --non-interactive
    - name: 'Floating Dependencies'

    - stage: 'Additional Tests'
      node_js: 10
    - node_js: 8
    - node_js: 6

    - stage: 'Deploy'
      name: 'Publish to npm'
      install:
        - yarn install --non-interactive
      script: yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
