language: node_js
sudo: required
dist: trusty
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
  - '8'
after_success:
  - yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
